import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <ul>
            <li>
              <ul>
                <li>
                  <Link href="/erp">ERP</Link>
                </li>
                <li>
                  <Link href="/erp/students">Add students</Link>
                </li>
                <li>
                  <Link href="/erp/teachers">Add Teachers</Link>
                </li>
                <li>
                  <Link href="/erp/subjects">Add subjects</Link>
                </li>
                <li>
                  <Link href="/erp/exams">Add exam</Link>
                </li>
                <li>
                  <Link href="/erp/schools">Add school</Link>
                </li>
              </ul>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
